---
# Global Variables for 'hypervisors' Inventory Group

live_migration: True
nested_virt: False
kernel_same_page_merging: False
dhcp: "off"
snat: "off"
ceilometer: "on"
glance: "off"
multipath: False
nova_instances_path: /opt/pf9/data/instances/
neutron_ovs_allow_dhcp_vms: "False"
neutron_ovs_bridge_name: "br-pf9, br-sriov"
neutron_ovs_bridge_mappings: "external:br-pf9, sriov:br-sriov"
ceilometer_customize: False
ceilometer_cpu_interval: 600

####################
# SRIOV
####################

sriov: "on"
physical_device_mappings: ""
pci_passthrough_whitelist: "{}"
